name: On PR Merged into Develop

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    #    runs-on: self-hosted
    steps:
      - name: escape pull request title
        run: |
          import json
          import os
          import shlex
          with open('${{ github.event_path }}') as fh:
              event = json.load(fh)
          title = shlex.quote(event['pull_request']['title'])
          body = shlex.quote(event['pull_request']['body'])
          with open(os.environ['GITHUB_ENV'], 'a') as fh:
              print(f'PR_TITLE={title}', file=fh)
              print(f'PR_BODY={body}', file=fh)
        shell: python3 {0}
      - name: show variables
        run: echo $GITHUB_ENV
