name: On PR Merged into Develop

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    #    runs-on: self-hosted
    steps:
      - name: strip quotes from PR body and title
        run: |
          import json
          import os
          import shlex
          import re
          with open('${{ github.event_path }}') as fh:
              event = json.load(fh)
          title = shlex.quote(event['pull_request']['title'])
          stripped_title = re.sub("[\"\']", "", title)
          body = shlex.quote(event['pull_request']['body'])
          stripped_body = re.sub("[\"\']", "", body)
          with open(os.environ['GITHUB_ENV'], 'a') as fh:
              print(f'PR_TITLE>>EOF\n{stripped_title}\nEOF', file=fh)
              print(f'PR_BODY>>EOF\n{stripped_body}\nEOF', file=fh)
        shell: python3 {0}
      - name: show variables
        run: echo $GITHUB_ENV
